# Generated by Django 3.0.2 on 2020-03-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200326_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcodesms',
            name='code',
            field=models.PositiveSmallIntegerField(default=24749),
        ),
    ]
