# Generated by Django 2.2.10 on 2020-02-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.PositiveIntegerField(choices=[(1, 'PrivetBank'), (2, 'MonoBank'), (3, 'Vkurse'), (4, 'OTP-bank'), (5, 'TasCom-bank')]),
        ),
    ]
